insert into public.bandcamp_sources (bandcamp_url, genre, source, status)
values
  ('https://killmer.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://timetheft.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://bonusroomband.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://thewaysidesmusic.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://candycigsmusic.bandcamp.com/', 'Indie Pop', 'legacy-json', 'active'),
  ('https://gvthdvddy.bandcamp.com/', 'Alternative', 'legacy-json', 'active'),
  ('https://uncannyvalleygirlspdx.bandcamp.com/', 'Punk', 'legacy-json', 'active'),
  ('https://shayleeband.bandcamp.com/', 'Post-Rock', 'legacy-json', 'active'),
  ('https://aninvisiblejet.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://essieandthehum.bandcamp.com/', 'Indie Folk', 'legacy-json', 'active'),
  ('https://hearfrontiermedicine.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://blond-noise.bandcamp.com/', 'Experimental', 'legacy-json', 'active'),
  ('https://longdeer.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://orbit17.bandcamp.com/', 'Electronic', 'legacy-json', 'active'),
  ('https://theupkeeps.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://fieldsofsilver.bandcamp.com/', 'Folk', 'legacy-json', 'active'),
  ('https://thequickandeasyboys.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://terriblepop.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://glasssuburban.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://reigncycle.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://greatyear.bandcamp.com/', 'Emo', 'legacy-json', 'active'),
  ('https://wellkinda.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://lionsoftheinterstate.bandcamp.com/', 'Indie Pop', 'legacy-json', 'active'),
  ('https://trashpandagokart.bandcamp.com/', 'Punk', 'legacy-json', 'active'),
  ('https://bikefightband.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://theeyeseeyous.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://blisterpdx.bandcamp.com/', 'Punk', 'legacy-json', 'active'),
  ('https://newvictorian.bandcamp.com/', 'Shoegaze / Dream Pop', 'legacy-json', 'active'),
  ('https://etfondle.bandcamp.com/', 'Singer-songwriter', 'legacy-json', 'active'),
  ('https://rosegerbermusic.bandcamp.com/', 'Country / Alt-Country', 'legacy-json', 'active'),
  ('https://fountainparkapts.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://buddywynkoop.bandcamp.com/', 'Punk', 'legacy-json', 'active'),
  ('https://mhimoh.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://kingropes.bandcamp.com/', 'Americana', 'legacy-json', 'active'),
  ('https://whenwemet.bandcamp.com/', 'Alternative', 'legacy-json', 'active'),
  ('https://guerobrown.bandcamp.com/', '', 'legacy-json', 'active'),
  ('https://slowpony1.bandcamp.com/', 'Country / Alt-Country', 'legacy-json', 'active'),
  ('https://cedarlange.bandcamp.com/', 'Alternative', 'legacy-json', 'active'),
  ('https://bandski.bandcamp.com/', 'Alternative', 'legacy-json', 'active'),
  ('https://itsglen.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://kelpwanted.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://badquitters.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://shimetheband.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://treefrogtheband.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://slowrosary.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://trashasaurusrex.bandcamp.com/', 'Punk', 'legacy-json', 'active'),
  ('https://sheaisely.bandcamp.com/', 'Singer-songwriter', 'legacy-json', 'active'),
  ('https://daveybones.bandcamp.com/', 'Post-punk', 'legacy-json', 'active'),
  ('https://thehoothoots.bandcamp.com/', 'Pop', 'legacy-json', 'active'),
  ('https://billyandthedreamboats.bandcamp.com/', 'Indie Pop', 'legacy-json', 'active'),
  ('https://blip206.bandcamp.com/', 'Emo', 'legacy-json', 'active'),
  ('https://tiny-lion.bandcamp.com/', 'Emo', 'legacy-json', 'active'),
  ('https://divorcedhorses.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active'),
  ('https://allfriendshere.bandcamp.com/', 'Alternative', 'legacy-json', 'active'),
  ('https://susurrusstation.bandcamp.com/', 'Alternative', 'legacy-json', 'active'),
  ('https://jochulina.bandcamp.com/', 'Indie Pop', 'legacy-json', 'active'),
  ('https://masonmctell.bandcamp.com/', 'Americana', 'legacy-json', 'active'),
  ('https://kinziesteele.bandcamp.com/', 'World / Global', 'legacy-json', 'active'),
  ('https://bory.bandcamp.com/', 'Rock', 'legacy-json', 'active'),
  ('https://jackietulsa.bandcamp.com/', 'Indie Rock', 'legacy-json', 'active')
on conflict (bandcamp_url) do update
set
  genre = excluded.genre,
  source = public.bandcamp_sources.source,
  status = case
    when public.bandcamp_sources.status = 'hidden' then 'hidden'
    else 'active'
  end;
