create table if not exists public.shows (
  id bigint generated by default as identity primary key,
  source_id text not null unique,
  venue_name text not null,
  title text not null,
  starts_at timestamptz not null,
  url text not null,
  scraped_at timestamptz not null default now()
);

create index if not exists shows_starts_at_idx on public.shows (starts_at);
create index if not exists shows_venue_name_idx on public.shows (venue_name);

alter table public.shows enable row level security;

drop policy if exists "Shows are publicly readable" on public.shows;
create policy "Shows are publicly readable"
  on public.shows
  for select
  using (true);
